/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.finalfantasysports.player;

public class Player {
    public static String someLibraryMethod() {
        return "Hi George!";
    }
}
