/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.finalfantasysports.eureka;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.netflix.eureka.server.EnableEurekaServer;

@EnableEurekaServer
@SpringBootApplication
public class FantasyEurekaApplication {
    public static void main(String[] args) {
        SpringApplication.run(FantasyEurekaApplication.class, args);
    }
}
